### ISSUE TITLE
formatError is not working for me

### ISSUE THREAD

**Issue by Cyberlane** [thebigredgeek/apollo-errors#3]
Things to note, I am using `graphql-server-express` version `0.6.0`, and I have hooked up `formatError` to my graphqlExpress, it just doesn't seem to work.

I created a new error with

```js
export const FetchError = createError('FetchError' , { message: 'blark' });
```

I used the error

```js
// data is the message body from a node-fetch
throw new FetchError({ data });
```

and I receive the following from GraphQL

```json
{
  "data": null,
  "errors": [
    {
      "message": "ApolloError: FetchError/::/2017-03-13T14:42:02.244Z/::/null/::/{\"errorGroup\":\"UNAUTHORIZED\",\"errorCode\":\"AUT_00011\",\"errorMessage\":\"Invalid session cookie\"}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "installation"
      ]
    }
  ]
}
```

Am I missing something obvious, or did I find a bug?

**Comment by thebigredgeek** [comment]
@Cyberlane can you paste a snippet showing me how you are hooking up formatErrors?

**Comment by Cyberlane** [comment]
@thebigredgeek sure, no problem. The code still needs a little refactoring to be clearer, right now I am just trying to make things work.

```js
  graphQLServer.use('/graphql',
    bodyParser.json(),
    (req, res, next) => fetchWithCookies(req, next, baseUrl, context),
    graphqlExpress({
      formatError,
      schema,
      context,
      rootValue: {},
    }));
```

`bodyParser` => `require('body-parser')`
`fetchWithCookies`  => my own wrapper around `node-fetch` to inject cookies
Everything else should make sense, but please ask if anything is unclear please shout!

**Comment by thebigredgeek** [comment]
@Cyberlane Interesting.  I'll definitely look into this later on this week.  It might be a regression with newer versions of `graphql-server`.

**Comment by thebigredgeek** [comment]
@Cyberlane can you write a wrapper function and `console.log` the raw error like this:

```javascript

{
  formatError: e => {
    console.trace(e);
    return formatError(e)
  }
}
```

**Comment by thebigredgeek** [comment]
I was unable to reproduce on `graphql-server-express` 0.6.0.  Release 1.4.0 in just a couple minutes though, so why don't you try that out and see if it works?

**Comment by Cyberlane** [comment]
@thebigredgeek sorry for the late reply... time zones!


Before doing the update I had
```
Trace: { Error: ApolloError: FetchError/::/2017-03-15T08:05:55.133Z/::/null/::/{"errorGroup":"UNAUTHORIZED","errorCode":"AUT_00011","errorMessage":"Invalid session cookie"}
```

I have now upgraded to `1.4.0` as you suggested, and now my response looks like:

```json
{
  "data": null,
  "errors": [
    {
      "message": "UnAuthorised: blark",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "installation"
      ]
    }
  ]
}
```

and the trace looks like
```
Trace: { Error: UnAuthorised: blark
    at C:\path\some-file.js:6:31
    at tryCatch (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:195:12)
    at invokeCallback (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:210:13)
    at publish (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:178:7)

    at publishRejection (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:120:3)
    at flush (C:\path\node_modules\es6-promise\dist\lib\es6-promise\asap.js:98:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'UnAuthorised: blark',
  locations: [ { line: 2, column: 3 } ],
  path: [ 'installation' ] }
    at Object.formatError (C:\path\graphql-server.js:21:17)
    at C:\path\node_modules\graphql-server-core\src\runQuery.ts:75:30
    at Array.map (native)
    at format (C:\path\node_modules\graphql-server-core\src\runQuery.ts:72:23)
    at C:\path\node_modules\graphql-server-core\src\runQuery.ts:140:38
    at tryCatch (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:195:12)
    at invokeCallback (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:210:13)
    at publish (C:\path\node_modules\es6-promise\dist\lib\es6-promise\-internal.js:178:7)

    at flush (C:\path\node_modules\es6-promise\dist\lib\es6-promise\asap.js:98:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

So it's a change, but it's still not working.

I am on the Apollo slack if it's easier to ask a few questions there to get to the bottom of this issue.

**Comment by Cyberlane** [comment]
Turns out to be a non-issue. Further down in my chain of code I was doing

```js
Promise.all(...).catch((error => { log(error); throw new Error(error); });
```

when I should have had

```js
Promise.all(...).catch((error => { log(error); throw error; });
```

Problem is solved.
